version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: pgweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    container_name: postgres
