// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BusinessInfo struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Address     *string   `json:"address"`
	ProductIds  []*string `json:"product_ids"`
}

type BusinessUser struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Product struct {
	ID          string `json:"id"`
	BusinessID  string `json:"business_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}

type DeleteBusinessInfo struct {
	ID string `json:"id"`
}

type DeleteBusinessUsers struct {
	ID string `json:"id"`
}

type DeleteProducts struct {
	ID string `json:"id"`
}

type NewBusinessInfo struct {
	UserID      string    `json:"user_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ProductIds  []*string `json:"product_ids"`
}

type NewBusinessUsers struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewProducts struct {
	BusinessID  string `json:"business_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int    `json:"price"`
}

type UpdateBusinessInfo struct {
	ID          string    `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Address     *string   `json:"address"`
	ProductIds  []*string `json:"product_ids"`
}

type UpdateBusinessUsers struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

type UpdateProducts struct {
	ID          string  `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Price       *int    `json:"price"`
}
