// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BusinessUser struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewBusinessUsers struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
